joueurs:
    path: /joueurs
    controller: App\Controller\JoueurController::index

matchs:
    path: /matchs
    controller: App\Controller\MatchsController::index

equipes:
    path: /equipes
    controller: App\Controller\EquipeController::index

